# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none  

resources:
  pipelines:
    - pipeline: ci-pipeline
      source: ci-pipeline
      trigger:
        branches:
          include:
            - main  
            - dev
        
jobs:
  - job: dependentJob
    steps:
      - script: echo "Pipeline A completed successfully, now running Pipeline B"
