trigger: none  

resources:
  pipelines:
    - pipeline: ci-pipeline
      source: ci-pipeline
      trigger: true

stages:
  - stage: deploy
    condition: and(succeeded(), ne(variables['resources.pipeline.ci-pipeline.reason'], 'PullRequest'))
    jobs:
      - job: deployJob
        steps:
          - script: echo "Deploying since CI was not triggered by a PR"
