# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches: # Branch names to include or exclude for triggering a run.
    include:
    - '*'
    #- refs/tags/*
  tags:
    include:
    - R2.*
pool:
  vmImage: ubuntu-latest


pr:
  branches:
    include:
      - '*'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
